# Copyright (C) 2016-2018 DeathCore <http://www.noffearrdeathproject.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# This file is run right before CMake starts configuring the sourcetree

# Example: Force CMAKE_INSTALL_PREFIX to be preloaded with something before
# doing the actual first "configure"-part - allows for hardforcing
# destinations elsewhere in the CMake buildsystem (commented out on purpose)

sudo: false
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libboost1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-iostreams1.55-dev
      - libboost-program-options1.55-dev
      - libboost-regex1.55-dev
      - libboost-system1.55-dev
      - libboost-thread1.55-dev
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev

services:
  - mysql

before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..
  - chmod +x contrib/check_updates.sh

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -udeathcore -pdeathcore auth < sql/base/auth_database.sql
  - ./contrib/check_updates.sh auth 3.3.5 auth
  - mysql -udeathcore -pdeathcore characters < sql/base/characters_database.sql
  - ./contrib/check_updates.sh characters 3.3.5 characters
  - mysql -udeathcore -pdeathcore world < sql/base/dev/world_database.sql
  - cat sql/updates/world/3.3.5/*.sql | mysql -udeathcore -pdeathcore world
  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make -j 4 -k && make install
  - cd check_install/bin
  - ./authserver --version
  - ./worldserver --version
